export const AGREGAR_TARJETA = 'ADD_TARJETA';
export const ELIMINAR_TARJETA = 'DELETE_TARJETA';
export const INICIAR_SESION = 'INICIAR_SESION';
export const CERRAR_SESION = 'CERRAR_SESION';
export const RECUPERAR_TOKEN = 'RECUPERAR_TOKEN';

